---

- name: Ensure local certs directory exists
  file:
    path: "/usr/local/share/ca-certificates"
    recurse: true
    state: directory

- name: Copy gitlab server's public key to gitlab-runner
  copy:
    src: "{{gitlab_runner_coordinator_cert_path}}"
    dest: "/usr/local/share/ca-certificates/"
    owner: root
    group: root
    mode: 0644

- name: Update cert index
  command: /usr/sbin/update-ca-certificates
  when: (gitlab_runner_connect_enable == true)
